name: rutviksandbox

on: 
  push:
<<<<<<< HEAD
    branches: [ main ]
  pull_request:
    branches: [ main ]
=======
    branches: [ master ]
  pull_request:
    branches: [ master ]
>>>>>>> 2ec7c887dae0e0ac2aa1e442c60f30cc56e73920

jobs:
  build: 
    runs-on: self-hosted
  
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.Js
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i
          npm run begin
          npm run build

