name: rutviksandbox

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: self-hosted
  
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.Js
        uses: actions/setup-node@v1

      - run: |
          cd src/ProjectsService
          npm install
          node ProjectsService.js

